const List<Map<String, dynamic>> solarSystem = [
  {
    "age":4.603,
    "gif": "asset/3DModal/sun.gif",
    "name": "Sun",
    "type": "Star",
    "diameter_km": 1391016,
    "mass_kg": 1.989e30,
    "gravity_m_s2": 274,
    "orbital_period_days": 0,
    "distance_from_sun_km": 0,
    "description":
    "The Sun is the center of our Solar System, a massive ball of hot plasma that provides energy to all planets.",
  },
  {
    "age":4.503,
    "gif": "asset/3DModal/mercury.gif",
    "name": "Mercury",
    "type": "Planet",
    "diameter_km": 4879,
    "mass_kg": 3.301e23,
    "gravity_m_s2": 3.7,
    "orbital_period_days": 88,
    "distance_from_sun_km": 57910000,
    "description":
    "Mercury is the smallest planet and the closest to the Sun, experiencing extreme temperature variations.",
  },
  {
    "age":4.503,
    "gif": "asset/3DModal/venus.gif",
    "name": "Venus",
    "type": "Planet",
    "diameter_km": 12104,
    "mass_kg": 4.867e24,
    "gravity_m_s2": 8.87,
    "orbital_period_days": 225,
    "distance_from_sun_km": 108200000,
    "description":
    "Venus has a thick, toxic atmosphere and the hottest surface temperatures in the Solar System.",
  },
  {
    "age":4.543,
    "gif": "asset/3DModal/earth.gif",
    "name": "Earth",
    "type": "Planet",
    "diameter_km": 12742,
    "mass_kg": 5.972e24,
    "gravity_m_s2": 9.81,
    "orbital_period_days": 365,
    "distance_from_sun_km": 149600000,
    "description":
    "Earth is the only known planet to support life, with a vast diversity of ecosystems and liquid water.",
  },
  {
    "age":4.53,
    "gif": "asset/3DModal/moon.gif",
    "name": "Moon",
    "type": "Moon",
    "diameter_km": 3474,
    "mass_kg": 7.342e22,
    "gravity_m_s2": 1.62,
    "orbital_period_days": 27.3,
    "distance_from_sun_km": 384400,
    "description":
    "The Moon is Earth's only natural satellite, influencing tides and stabilizing Earth's axial tilt.",
  },
  {
    "age":4.603,
    "gif": "asset/3DModal/mars.gif",
    "name": "Mars",
    "type": "Planet",
    "diameter_km": 6779,
    "mass_kg": 6.417e23,
    "gravity_m_s2": 3.71,
    "orbital_period_days": 687,
    "distance_from_sun_km": 227900000,
    "description":
    "Mars is known as the Red Planet due to its iron-rich soil and has the tallest volcano in the Solar System.",
  },
  {
    "age":4.603,
    "gif": "asset/3DModal/jupiter.gif",
    "name": "Jupiter",
    "type": "Planet",
    "diameter_km": 139820,
    "mass_kg": 1.898e27,
    "gravity_m_s2": 24.79,
    "orbital_period_days": 4333,
    "distance_from_sun_km": 778500000,
    "description":
    "Jupiter is the largest planet, famous for its Great Red Spot and many moons.",
  },
  {
    "age":4.503,
    "gif": "asset/3DModal/saturn.gif",
    "name": "Saturn",
    "type": "Planet",
    "diameter_km": 116460,
    "mass_kg": 5.683e26,
    "gravity_m_s2": 10.44,
    "orbital_period_days": 10759,
    "distance_from_sun_km": 1434000000,
    "description":
    "Saturn is known for its stunning ring system made of ice and rock particles.",
  },
  {
    "age":4.503,
    "gif": "asset/3DModal/uranus.gif",
    "name": "Uranus",
    "type": "Planet",
    "diameter_km": 50724,
    "mass_kg": 8.681e25,
    "gravity_m_s2": 8.69,
    "orbital_period_days": 30687,
    "distance_from_sun_km": 2871000000,
    "description":
    "Uranus rotates on its side, possibly due to a massive collision in the past, and has a faint ring system.",
  },
  {
    "age":4.503,
    "gif": "asset/3DModal/neptune.gif",
    "name": "Neptune",
    "type": "Planet",
    "diameter_km": 49244,
    "mass_kg": 1.024e26,
    "gravity_m_s2": 11.15,
    "orbital_period_days": 60190,
    "distance_from_sun_km": 4495000000,
    "description":
    "Neptune is the windiest planet, with storms raging at supersonic speeds, and has a deep blue color.",
  },
  {
    "age":4.5,
    "gif": "asset/3DModal/pluto.gif",
    "name": "Pluto",
    "type": "Dwarf Planet",
    "diameter_km": 2376,
    "mass_kg": 1.309e22,
    "gravity_m_s2": 0.62,
    "orbital_period_days": 90560,
    "distance_from_sun_km": 5906000000,
    "description":
    "Pluto, once considered the ninth planet, is now classified as a dwarf planet and is part of the Kuiper Belt.",
  },
];